<?php

namespace App\Models;


use App\Observers\ExcavatorCostObserver;

class ExcavatorCost extends EloquentModel
{
    //
    protected $table='excavator_cost';

    protected $guarded=[];


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::observe(ExcavatorCostObserver::class);
    }


    public function children() {
        return $this->hasMany(Category::class, 'parent_id', 'id');
    }

    /**
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @param  mixed  $type
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeParentId($query,$parent_id)
    {
        return $query->where('parent_id', $parent_id);
    }


    /**
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @param  mixed  $type
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeShow($query, $show=true)
    {
        return $query->where('show', $show?10:20);
    }

    public function fetchAll()
    {
        return $this->all()->toArray();
        /*return \Cache::rememberForever(static::getCacheKey(),function (){
            return $this->all()->toArray();
        });*/
    }
}
